"""The domain supervisor flags ungrounded claims. It does not rewrite answers.

P0-2: it used to overwrite `state["response"]` with an LLM-generated
`grounded_summary`. That silently discarded the mandatory clinical disclaimer
that `clinical_agent` appends, and replaced a reviewed answer with an unreviewed
one. These tests pin the invariant: the supervisor observes, it never edits.

P0-1: it also used to skip itself entirely when `_want_stream` was set, so a
streamed answer was never checked for grounding.
"""
from __future__ import annotations

import json

import pytest

from mao.agents.domain_supervisor import domain_supervisor_node
from mao.providers import gateway
from mao.providers.llm.base import ProviderResponse

_DISCLAIMER = (
    "\n\n---\n**IMPORTANT - AI Decision Support Only**\n"
    "This response is generated by an AI system to assist clinical decision-making."
)
_ANSWER = "Donepezil is first-line for mild Alzheimer's disease." + _DISCLAIMER


class FakeProvider:
    """Returns scripted text and records what it was asked."""

    name = "fake"

    def __init__(self, text: str = "{}", raises: bool = False) -> None:
        self.text = text
        self.raises = raises
        self.calls: list[dict] = []

    def complete(self, *, model_id, messages, temperature, max_tokens) -> ProviderResponse:
        if self.raises:
            raise RuntimeError("provider down")
        self.calls.append({"model_id": model_id, "messages": messages})
        return ProviderResponse(text=self.text)


@pytest.fixture
def bind_provider():
    bound: list[FakeProvider] = []

    def _bind(text: str = "{}", raises: bool = False) -> FakeProvider:
        provider = FakeProvider(text, raises=raises)
        gateway.set_provider(provider)
        bound.append(provider)
        return provider

    yield _bind
    gateway.reset_provider()


# ---------------------------------------------------------------------------
# P0-2 — the supervisor must never write state["response"]
# ---------------------------------------------------------------------------

def test_supervisor_does_not_overwrite_the_response(bind_provider):
    """Even when the model volunteers a rewritten answer, the response stands."""
    bind_provider(json.dumps({
        "grounded_summary": "A completely different answer with no disclaimer.",
        "ungrounded_claims": ["claim one"],
        "sources_used": ["paper.pdf"],
    }))

    state = {"response": _ANSWER, "retrieved_docs": ["chunk"], "web_results": []}
    out = domain_supervisor_node(state)

    assert out["response"] == _ANSWER
    assert "A completely different answer" not in out["response"]


def test_clinical_disclaimer_survives_the_supervisor(bind_provider):
    """The disclaimer is the control this defect destroyed. It must reach the user."""
    bind_provider(json.dumps({"grounded_summary": "Rewritten.", "ungrounded_claims": []}))

    out = domain_supervisor_node({"response": _ANSWER, "retrieved_docs": ["chunk"]})

    assert "IMPORTANT" in out["response"]
    assert "AI Decision Support Only" in out["response"]


def test_supervisor_writes_ungrounded_claims(bind_provider):
    bind_provider(json.dumps({"ungrounded_claims": ["claim one", "claim two"]}))

    out = domain_supervisor_node({"response": _ANSWER, "retrieved_docs": ["chunk"]})

    assert out["ungrounded_claims"] == ["claim one", "claim two"]


def test_supervisor_uses_the_registered_reconcile_prompt(bind_provider):
    """The v2 prompt is the one that forbids rewriting; inline text would drift."""
    from mao.prompts import get_prompt

    provider = bind_provider("{}")
    domain_supervisor_node({"response": _ANSWER, "retrieved_docs": ["chunk"]})

    spec = get_prompt("domain_supervisor.reconcile")
    assert spec.version == "2.0.0"
    assert provider.calls[0]["messages"][0]["content"] == spec.template


@pytest.mark.parametrize("bad", ["not json at all", "", "{broken", "[]"])
def test_malformed_output_leaves_the_response_alone(bind_provider, bad):
    bind_provider(bad)

    out = domain_supervisor_node({"response": _ANSWER, "retrieved_docs": ["chunk"]})

    assert out["response"] == _ANSWER
    assert out["ungrounded_claims"] == []


def test_provider_failure_leaves_the_response_alone(bind_provider):
    bind_provider(raises=True)

    out = domain_supervisor_node({"response": _ANSWER, "retrieved_docs": ["chunk"]})

    assert out["response"] == _ANSWER
    assert out["ungrounded_claims"] == []


# ---------------------------------------------------------------------------
# P0-1 — supervision must not depend on the transport
# ---------------------------------------------------------------------------

def test_streaming_request_with_an_answer_is_still_checked(bind_provider):
    provider = bind_provider(json.dumps({"ungrounded_claims": ["unsupported claim"]}))

    out = domain_supervisor_node({
        "response": _ANSWER,
        "retrieved_docs": ["chunk"],
        "_want_stream": True,
    })

    assert len(provider.calls) == 1, "a streamed answer must still be checked"
    assert out["ungrounded_claims"] == ["unsupported claim"]


def test_streamed_and_buffered_states_produce_the_same_result(bind_provider):
    """Transport is not an input to grounding."""
    bind_provider(json.dumps({"ungrounded_claims": ["c"]}))

    streamed = domain_supervisor_node({
        "response": _ANSWER, "retrieved_docs": ["chunk"], "_want_stream": True,
    })
    buffered = domain_supervisor_node({
        "response": _ANSWER, "retrieved_docs": ["chunk"],
    })

    assert streamed["ungrounded_claims"] == buffered["ungrounded_claims"]
    assert streamed["response"] == buffered["response"]


def test_empty_response_skips_without_calling_the_model(bind_provider):
    """Nothing to reconcile — skipped on its own merits, not because of streaming."""
    provider = bind_provider("{}")

    out = domain_supervisor_node({"response": "", "retrieved_docs": ["chunk"]})

    assert provider.calls == []
    assert out["ungrounded_claims"] == []
