"""
mao/agents/clinical_agent.py
------------------------------
Clinical AI assistant — MRI prediction + report analysis + research retrieval.

Route trigger: intent == "clinical"

When to route here:
  - User uploads a 2D MRI image (PNG/JPG) for Alzheimer's stage prediction
  - User uploads a PDF medical report for analysis
  - Patient/doctor asks: "What does this scan show?", "What stage is this?"
  - "Analyse this report", "My patient has LMCI — what treatment options exist?"
  - Any clinical decision-support question about Alzheimer's / neuroimaging

Three sub-modes (auto-detected from state["metadata"]):
  1. MRI image  — metadata["image_b64"] or metadata["image_url"] present
  2. PDF report — metadata["report_b64"] or metadata["report_path"] present
  3. Text only  — no file; knowledge question with clinical context

All three modes:
  - Search Mem0 memories before LLM
  - Retrieve from GraphRAG (AD research PDFs)
  - ALWAYS append medical disclaimer

Mode 1 (MRI) also:
  - Runs EfficientNetB3 prediction (CN/EMCI/LMCI/AD + confidence)
  - Web search for latest clinical evidence

Mode 2 (Report) also:
  - Extracts text from PDF (pypdf)
  - Structured extraction: diagnosis, biomarkers, medications, tests
  - Map-reduce summarization for long reports
  - Web search for clinical guidelines

Models:
  - EfficientNetB3 (Saiarun/b3 on HuggingFace)  — prediction
  - llama3.1:8b                                  — reasoning + synthesis
  - mistral                                      — structured extraction (faster)

Integration points:
  - mao/models/mri_predictor.py  EfficientNetB3 wrapper
  - mao/rag/retriever.py         GraphRAG 5-step pipeline
  - mao/memory/mem0_handler.py   Mem0 search/save
  - core/state.py                MAOState contract
"""

from __future__ import annotations

import base64
import json
import logging
from typing import Any

import requests
from mao.core import llm as groq_llm

from mao.core.config import cfg, MRI_CONFIDENCE_GATE, TOKEN_BUDGET
from mao.core.state import MAOState
from mao.core.token_counter import truncate_to_budget
from mao.eval.nli_checker import check_all_claims
from mao.memory.mem0_handler import build_system_prompt, save_memory, search_memories
from mao.rag.retriever import retrieve
from mao.report.report_card import SourceEntry, build_report_card

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Medical disclaimer — always appended, never omitted
# ---------------------------------------------------------------------------

_DISCLAIMER = """

---
**IMPORTANT — AI Decision Support Only**
This response is generated by an AI system to assist clinical decision-making.
It is NOT a medical diagnosis and must NOT replace professional medical judgement.
All findings must be reviewed and confirmed by a licensed physician or specialist
before any clinical action is taken.
"""

# ---------------------------------------------------------------------------
# System prompts
# ---------------------------------------------------------------------------

_CLINICAL_SYSTEM = """\
You are a clinical AI assistant specializing in Alzheimer's disease and neuroimaging.
You provide evidence-based decision support for healthcare professionals and patients.

Core rules:
  - Always base your response on the provided context (research papers, prediction results, web sources)
  - Cite sources by their filename and chunk ID when referencing research papers
  - Never fabricate medical facts or invent statistics
  - Structure your response with clear section headers
  - The medical disclaimer will be appended automatically — do not add your own
  - Use plain, accessible language alongside clinical terminology
"""

_EXTRACTION_SYSTEM = """\
You are a medical data extraction assistant.
Extract structured information from the medical report below.
Respond ONLY with valid JSON matching this schema (use null for missing fields):
{
  "diagnosis": "string or null",
  "biomarkers": {"marker_name": "value_with_unit"},
  "medications": ["list of current medications"],
  "recommended_tests": ["list of recommended tests"],
  "key_findings": ["list of key clinical findings"]
}
"""

# ---------------------------------------------------------------------------
# Main node
# ---------------------------------------------------------------------------

def clinical_node(state: MAOState) -> MAOState:
    """LangGraph node: clinical decision support."""
    user_query: str = state.get("pii_scrubbed_query") or state["user_query"]
    user_id: str    = state["user_id"]
    domain: str     = state.get("domain", "alzheimer")
    metadata: dict  = state.get("metadata", {})
    memory_context: str = state.get("memory_context", "")

    if not memory_context:
        memory_context = search_memories(user_query, user_id)
        state["memory_context"] = memory_context

    # --- Detect sub-mode ---
    has_image  = bool(metadata.get("image_b64") or metadata.get("image_url"))
    has_report = bool(metadata.get("report_b64") or metadata.get("report_path"))

    if has_image:
        response, result_meta = _handle_mri_image(user_query, metadata, memory_context, domain=domain)
    elif has_report:
        response, result_meta = _handle_pdf_report(user_query, metadata, memory_context, domain=domain)
    else:
        response, result_meta = _handle_text_question(user_query, memory_context, domain=domain)

    # --- NLI entailment check on key claims ---
    chunks_text = " ".join(
        c.text[:300] if hasattr(c, "text") else str(c)
        for c in result_meta.get("_ranked_chunks", [])[:4]
    )
    if chunks_text:
        claims = [s.strip() for s in response.split(".") if len(s.strip()) > 20][:10]
        nli_flags = check_all_claims(claims, chunks_text) if claims else []
    else:
        nli_flags = []

    # --- Uncertainty flag from MRI confidence ---
    prediction = result_meta.get("prediction", {})
    mri_confidence = float(prediction.get("confidence", 1.0))
    uncertainty_flag = mri_confidence < MRI_CONFIDENCE_GATE if prediction else False

    # --- Build ReportCard ---
    sources = [
        SourceEntry(tool="retriever", snippet=str(s.get("snippet", ""))[:500], query=user_query)
        for s in result_meta.get("sources", [])[:3]
    ]
    report = build_report_card(
        stage=prediction.get("prediction", "N/A") if prediction else "N/A",
        stage_interpretation=_interpret_stage(prediction.get("prediction", "") if prediction else ""),
        clinical_significance=response[:300],
        medications=[],
        literature_evidence=[s.get("source", "") for s in result_meta.get("sources", [])[:3]],
        recommended_next_steps=["Consult a specialist for comprehensive evaluation."],
        confidence_score=mri_confidence if prediction else 1.0,
        sources=sources,
        uncertainty_flag=uncertainty_flag,
    )

    response = response + _DISCLAIMER
    save_memory(user_query, response, user_id)

    state["response"]     = response
    state["agent_used"]   = "clinical"
    state["metadata"]     = {**metadata, **{k: v for k, v in result_meta.items() if not k.startswith("_")}}
    state["report_card"]  = report.to_dict()
    state["nli_flags"]    = nli_flags
    state["uncertainty_flag"] = uncertainty_flag
    return state


def _interpret_stage(stage: str) -> str:
    return {
        "CN":   "Cognitively normal — no significant impairment detected.",
        "EMCI": "Early mild cognitive impairment — early intervention recommended.",
        "LMCI": "Late mild cognitive impairment — closer monitoring advised.",
        "AD":   "Alzheimer's disease — comprehensive care planning recommended.",
    }.get(stage, "Stage information unavailable.")


# ---------------------------------------------------------------------------
# Mode 1 — MRI image
# ---------------------------------------------------------------------------

def _handle_mri_image(
    user_query: str,
    metadata: dict,
    memory_context: str,
    domain: str = "alzheimer",
) -> tuple[str, dict]:
    """Predict → retrieve → web search → synthesize."""

    # Step 1: Run EfficientNetB3
    prediction = _run_mri_prediction(metadata)

    if prediction.get("error"):
        logger.warning("MRI prediction failed: %s", prediction["error"])
        pred_block = "MRI prediction could not be completed (model unavailable)."
        augmented_query = user_query
    else:
        label      = prediction["prediction"]
        full_label = prediction["full_label"]
        confidence = prediction["confidence"]
        scores     = prediction["all_scores"]
        pred_block = _format_prediction(label, full_label, confidence, scores)
        augmented_query = (
            f"Clinical implications and treatment considerations for "
            f"{full_label} ({label}) in Alzheimer's disease. {user_query}"
        )

    # Step 2: GraphRAG retrieval
    try:
        ranked_chunks = retrieve(augmented_query, domain=domain)
    except Exception as exc:  # noqa: BLE001
        logger.error("GraphRAG retrieval failed: %s", exc)
        ranked_chunks = []

    research_block = _format_sources(ranked_chunks)

    # Step 3: Web search for latest evidence
    web_block = _web_search_clinical(
        f"{prediction.get('prediction', '')} Alzheimer's disease treatment 2024"
        if not prediction.get("error") else user_query
    )

    # Step 4: Synthesize
    system_prompt = build_system_prompt(_CLINICAL_SYSTEM, memory_context)
    user_prompt = (
        f"User question: {user_query}\n\n"
        f"## MRI Prediction Result\n{pred_block}\n\n"
        f"## Relevant Research Papers\n{research_block}\n\n"
        f"## Current Clinical Evidence (Web)\n{web_block}\n\n"
        "Please synthesize the above into a structured clinical decision-support response. "
        "Include: interpretation, clinical significance, recommended next steps, and cited sources."
    )
    response = _call_llm(system_prompt, user_prompt)

    sources = [
        {"source": c.metadata.get("source", ""), "chunk_id": c.metadata.get("chunk_id", ""),
         "score": round(c.score, 4), "snippet": c.text[:300]}
        for c in ranked_chunks
    ]
    return response, {
        "mode": "mri_image",
        "prediction": prediction,
        "sources": sources,
        "chunks_retrieved": len(ranked_chunks),
        "_ranked_chunks": ranked_chunks,
    }


def _run_mri_prediction(metadata: dict) -> dict:
    """Call MRIPredictor with image from metadata."""
    try:
        from mao.models.mri_predictor import get_predictor
        predictor = get_predictor()
        if metadata.get("image_b64"):
            return predictor.predict(metadata["image_b64"])
        if metadata.get("image_url"):
            resp = requests.get(metadata["image_url"], timeout=15)
            resp.raise_for_status()
            return predictor.predict(resp.content)
        return {"error": "no image data found in metadata"}
    except Exception as exc:  # noqa: BLE001
        logger.error("MRI prediction call failed: %s", exc)
        return {"error": str(exc)}


def _format_prediction(label: str, full_label: str, confidence: float, scores: dict) -> str:
    lines = [
        f"**Predicted Stage: {full_label} ({label})**",
        f"Confidence: {confidence * 100:.1f}%",
        "",
        "All class probabilities:",
    ]
    for lbl, score in sorted(scores.items(), key=lambda x: x[1], reverse=True):
        bar = "#" * int(score * 20)
        lines.append(f"  {lbl:4s}: {score * 100:5.1f}%  {bar}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Mode 2 — PDF report
# ---------------------------------------------------------------------------

def _handle_pdf_report(
    user_query: str,
    metadata: dict,
    memory_context: str,
    domain: str = "alzheimer",
) -> tuple[str, dict]:
    """Extract PDF text → summarize → structured extraction → research → web → synthesize."""

    # Step 1: Get PDF text
    report_text = _extract_pdf_text(metadata)
    if not report_text:
        return (
            "Could not extract text from the provided PDF. "
            "Please ensure the file is a readable PDF.",
            {"mode": "pdf_report", "error": "pdf_extraction_failed"},
        )

    # Step 2: Structured extraction
    extracted = _extract_structured_fields(report_text)

    # Step 3: Summarize
    summary = _summarize_report(report_text, memory_context)

    # Step 4: GraphRAG retrieval on report content
    retrieval_query = report_text[:500]  # first 500 chars as retrieval seed
    if extracted.get("diagnosis"):
        retrieval_query = f"{extracted['diagnosis']} {retrieval_query}"
    try:
        ranked_chunks = retrieve(retrieval_query, domain=domain)
    except Exception as exc:  # noqa: BLE001
        logger.error("GraphRAG retrieval failed: %s", exc)
        ranked_chunks = []

    research_block = _format_sources(ranked_chunks)

    # Step 5: Web search for guidelines
    search_query = f"{extracted.get('diagnosis', 'Alzheimer disease')} clinical guidelines treatment 2024"
    web_block = _web_search_clinical(search_query)

    # Step 6: Synthesize
    system_prompt = build_system_prompt(_CLINICAL_SYSTEM, memory_context)

    extracted_text = json.dumps(extracted, indent=2) if extracted else "(extraction failed)"
    user_prompt = (
        f"User request: {user_query}\n\n"
        f"## Report Summary\n{summary}\n\n"
        f"## Extracted Clinical Data\n```json\n{extracted_text}\n```\n\n"
        f"## Relevant Research Papers\n{research_block}\n\n"
        f"## Clinical Guidelines (Web)\n{web_block}\n\n"
        "Provide a structured clinical decision-support response with sections:\n"
        "## Summary\n## Key Findings\n## Relevant Research\n## Clinical Guidance\n"
        "Always cite research papers by their filename and chunk ID."
    )
    response = _call_llm(system_prompt, user_prompt)

    sources = [
        {"source": c.metadata.get("source", ""), "chunk_id": c.metadata.get("chunk_id", ""),
         "score": round(c.score, 4), "snippet": c.text[:300]}
        for c in ranked_chunks
    ]
    return response, {
        "mode": "pdf_report",
        "extracted": extracted,
        "sources": sources,
        "chunks_retrieved": len(ranked_chunks),
        "report_length": len(report_text),
        "_ranked_chunks": ranked_chunks,
    }


def _extract_pdf_text(metadata: dict) -> str:
    """Extract text from PDF in metadata (base64 or file path)."""
    try:
        from pypdf import PdfReader
        import io
    except ImportError:
        logger.error("pypdf not installed. Run: pip install pypdf")
        return ""

    try:
        if metadata.get("report_b64"):
            pdf_bytes = base64.b64decode(metadata["report_b64"])
            reader = PdfReader(io.BytesIO(pdf_bytes))
        elif metadata.get("report_path"):
            reader = PdfReader(metadata["report_path"])
        else:
            return ""

        pages = []
        for page in reader.pages:
            try:
                text = page.extract_text() or ""
                if text.strip():
                    pages.append(text)
            except Exception:  # noqa: BLE001
                continue
        return "\n\n".join(pages)
    except Exception as exc:  # noqa: BLE001
        logger.error("PDF extraction failed: %s", exc)
        return ""


def _extract_structured_fields(report_text: str) -> dict:
    """Extract structured clinical data from report text."""
    prompt = (
        "Extract the following fields from this medical report as JSON: "
        "diagnosis, biomarkers, medications, tests.\n\n"
        f"Report:\n{report_text[:2000]}\n\n"
        "Return only valid JSON."
    )
    try:
        raw = groq_llm.chat(
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            max_tokens=512,
        ).strip()
        import json as _json
        # Extract JSON from response
        start = raw.find("{")
        end = raw.rfind("}") + 1
        return _json.loads(raw[start:end]) if start >= 0 else {}
    except Exception as exc:
        logger.error("Structured extraction failed: %s", exc)
        return {}


# ---------------------------------------------------------------------------
# Mode 3 — Text question only
# ---------------------------------------------------------------------------

def _handle_text_question(
    user_query: str,
    memory_context: str,
    domain: str = "alzheimer",
) -> tuple[str, dict]:
    """GraphRAG retrieval + synthesis with clinical framing."""
    try:
        ranked_chunks = retrieve(user_query, domain=domain)
    except Exception as exc:  # noqa: BLE001
        logger.error("GraphRAG retrieval failed: %s", exc)
        ranked_chunks = []

    research_block = _format_sources(ranked_chunks)

    system_prompt = build_system_prompt(_CLINICAL_SYSTEM, memory_context)
    user_prompt = (
        f"## Relevant Research\n{research_block}\n\n"
        f"User question: {user_query}\n\n"
        "Provide a clear, evidence-based answer citing the research sources above."
    )
    response = _call_llm(system_prompt, user_prompt)

    sources = [
        {"source": c.metadata.get("source", ""), "chunk_id": c.metadata.get("chunk_id", ""),
         "score": round(c.score, 4), "snippet": c.text[:300]}
        for c in ranked_chunks
    ]
    return response, {
        "mode": "text_question",
        "sources": sources,
        "chunks_retrieved": len(ranked_chunks),
        "_ranked_chunks": ranked_chunks,
    }


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _format_sources(ranked_chunks) -> str:
    """Format retrieved chunks with source filename, chunk_id, score, and snippet."""
    if not ranked_chunks:
        return "No relevant research found in knowledge base."
    lines = []
    for i, chunk in enumerate(ranked_chunks, 1):
        source   = chunk.metadata.get("source", "unknown")
        chunk_id = chunk.metadata.get("chunk_id", "—")
        score    = chunk.score
        snippet  = chunk.text[:400].replace("\n", " ")
        lines.append(
            f"[{i}] **{source}** (chunk: {chunk_id}, relevance: {score:.3f})\n"
            f"    {snippet}..."
        )
    return "\n\n".join(lines)


def _web_search_clinical(query: str) -> str:
    """Web search for clinical evidence — uses multi-provider fallback chain."""
    from mao.core.web_search import web_search

    results = web_search(query, num_results=4)
    if not results:
        return "No web results found."
    lines = []
    for r in results:
        title = r.get("title", "")
        body  = r.get("body", "")[:300]
        lines.append(f"- **{title}**\n  {body}")
    return "\n\n".join(lines)


def _call_llm(system_prompt: str, user_prompt: str) -> str:
    """Call Groq for clinical synthesis."""
    try:
        return groq_llm.chat(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_prompt},
            ],
            temperature=0.1,
            max_tokens=1024,
        ).strip()
    except Exception as exc:
        logger.error("Clinical LLM call failed: %s", exc)
        return f"Response generation failed: {exc}"


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    from mao.core.state import make_initial_state
    state = make_initial_state(
        "My patient has LMCI. What treatment options exist?",
        "user-test",
    )
    state = clinical_node(state)
    print(state["response"][:500])
    print("\nAgent:", state["agent_used"])
    print("Mode:", state["metadata"].get("mode"))
    print("Chunks:", state["metadata"].get("chunks_retrieved"))
