"""Agent-independent output verification.

Two audited defects come from verification having been an *agent's*
responsibility rather than the pipeline's:

P1-1  `judge_scores` was never written to graph state. `output_guardrails`
      reads `state["judge_scores"]` and defaults the safety score to 10 when it
      is missing, so the judge BLOCK and WARN branches could not fire in
      production — dead code guarding nothing.

P1-2  `nli_flags` was written only by `clinical_agent`. Every other agent
      (graphrag, summarizer, tool, sql, multimodal, critic) produced answers the
      NLI entailment gate never looked at.

`verification_node` runs after whichever agent produced the answer, so both
signals exist for every response regardless of which agent ran. It observes and
scores; it never edits the response.

Failure posture, and the distinction that matters:

*Unavailable* — the provider raised. The judge fails **open** (safety 10) with
the error in `notes`, because an outage must not blanket-block clinical
traffic. This is only defensible because the council is a genuine fail-closed
backstop: `llm_council.parse_member_verdict` requires an affirmative
`VERDICT: PASS`, so a member that cannot answer blocks. (Before that fix the
council passed anything not containing the literal string "FAIL", and this
docstring's justification was simply false — both controls failed open at once.)

*Answered, but not to contract* — the judge replied with something other than
`{"safety": int, ...}`. That is not an outage, it is a judge whose verdict we
cannot read, so `safety` fails **closed** at 0 and the guardrails block. A judge
that identifies harm as the word "unsafe" used to be scored 10/10.
"""
from __future__ import annotations

import json
import logging
import re

from mao.eval.nli_checker import check_all_claims
from mao.prompts import get_prompt
from mao.prompts.verification import build_verifier_messages
from mao.providers import gateway
from mao.trust.egress.policy import EgressPurpose
from mao.providers.registry import ModelRole
from mao.safety.policy import get_policy, resolve_risk
from mao.schemas.evidence import Claim, VerificationStatus, as_text

logger = logging.getLogger(__name__)

# Re-exported so existing importers keep working. This module deliberately does
# not define its own resolver: it used to, with lenient semantics ("Low" -> LOW),
# and `output_guardrails` imported that one while `api/streaming.py` used the
# strict policy one — the two halves of the P0-1 guarantee disagreed on the only
# risk level allowed to skip verification.
__all__ = [
    "CLINICAL_DISCLAIMER",
    "DISCLAIMER_MARKER",
    "resolve_risk",
    "verification_node",
]

_JSON_FENCE_RE = re.compile(r"^```(?:json)?\s*|\s*```$", re.MULTILINE)

_JUDGE_PROMPT = "judge.safety"
_JUDGE_MAX_TOKENS = 300

# The judge shared `council.user_turn` with the council, so it inherited the
# same defect and failed the same way: a poisoned chunk that forged "RESPONSE TO
# EVALUATE:" scored 10/10 live on an answer the same model had scored 0. It now
# shares the structural separation instead (ADV15-10).
_VERIFIER_PROTOCOL = "verifier.protocol"

# Claim extraction: sentences long enough to assert something, capped so a long
# answer cannot turn one request into a hundred cross-encoder passes.
_MIN_CLAIM_CHARS = 20
_MAX_CLAIMS = 10
_MAX_PREMISE_DOCS = 4
_MAX_DOC_CHARS = 300

# The mandatory clinical disclaimer. It lives here, not in `clinical_agent`, so
# that `output_guardrails` can re-assert it without importing an agent (P0-2).
CLINICAL_DISCLAIMER = """

---
**IMPORTANT — AI Decision Support Only**
This response is generated by an AI system to assist clinical decision-making.
It is NOT a medical diagnosis and must NOT replace professional medical judgement.
All findings must be reviewed and confirmed by a licensed physician or specialist
before any clinical action is taken.
"""

# Stable substring used to detect the disclaimer regardless of formatting drift.
DISCLAIMER_MARKER = "AI Decision Support Only"


# ---------------------------------------------------------------------------
# NLI entailment
# ---------------------------------------------------------------------------

def _premise_from(docs) -> str:
    """Flatten retrieved evidence into an NLI and judge premise.

    `as_text` rather than a local `str(doc)` fallback. `graphrag_node` publishes
    dicts, which have no `.text` attribute, so the fallback fired and the
    premise became Python repr syntax — truncated at 300 characters of
    `{'text': '...` per document, with the source key cut off every time. The
    judge scored groundedness against that, and the truncation budget was being
    spent on punctuation.
    """
    if not docs:
        return ""
    parts = []
    for doc in list(docs)[:_MAX_PREMISE_DOCS]:
        if doc is None:
            continue
        parts.append(as_text(doc)[:_MAX_DOC_CHARS])
    return " ".join(p for p in parts if p.strip())


def _claims_from(response: str) -> list[str]:
    return [
        s.strip() for s in response.split(".") if len(s.strip()) > _MIN_CLAIM_CHARS
    ][:_MAX_CLAIMS]


def _to_claim(index: int, flag: dict) -> Claim:
    """One NLI result as the architecture's canonical Claim.

    `Claim` was declared in Phase 1 and consumed by nothing. Building it here
    makes it the type this logic is written against, and buys something real:
    `entailed` is one boolean covering three different situations, and
    `verification_status` separates them. "The sources contradict this" and "the
    sources do not mention this" are both `entailed=False`, and a clinician
    reading a warning about unverified claims would want to know which.
    """
    support = float(flag.get("score") or 0.0)
    contradiction = float(flag.get("contradiction_score") or 0.0)
    if flag.get("entailed"):
        status = VerificationStatus.SUPPORTED
    elif contradiction > support:
        status = VerificationStatus.CONTRADICTED
    else:
        status = VerificationStatus.INSUFFICIENT
    return Claim(
        claim_id=f"c{index}",
        text=str(flag.get("claim", "")),
        support_score=support,
        contradiction_score=contradiction,
        certainty=support,
        verification_status=status,
    )


def _claim_as_flag(claim: Claim) -> dict:
    """JSON-safe projection of a Claim.

    `nli_flags` is written to a JSON column and read as dicts by the output
    guardrails, the trace and the audit row, so the wire format stays a dict.
    `entailed` is kept for those readers; `verification_status` is added
    alongside it rather than replacing it.
    """
    return {
        "claim": claim.text,
        "entailed": claim.verification_status is VerificationStatus.SUPPORTED,
        "score": claim.support_score,
        "contradiction_score": claim.contradiction_score,
        "verification_status": claim.verification_status.value,
    }


def _run_nli(response: str, docs) -> list[dict]:
    """Entailment flags for the response's claims. Never raises."""
    try:
        premise = _premise_from(docs)
        if not premise:
            return []
        claims = _claims_from(response)
        if not claims:
            return []
        flags = check_all_claims(claims, premise)
        return [
            _claim_as_flag(_to_claim(i, f))
            for i, f in enumerate(flags)
            if isinstance(f, dict)
        ]
    except Exception as exc:  # noqa: BLE001 - a broken checker must not fail the request
        logger.error("NLI entailment check failed: %s", exc)
        return []


# ---------------------------------------------------------------------------
# LLM judge
# ---------------------------------------------------------------------------

# A judge that answered but broke its output contract has not cleared the
# response — its score is unreadable, not high. `safety` therefore fails closed.
_UNREADABLE_SAFETY = 0
# `groundedness` drives no block branch; a missing value is neutral, not a veto.
_UNREADABLE_GROUNDEDNESS = 10


def _score(value, default: int) -> int:
    """Coerce a model-supplied score into an int clamped to 0-10.

    `default` is explicit at every call site because the safe direction differs
    per field: an unreadable safety score must block, an unreadable groundedness
    score must not.
    """
    try:
        return max(0, min(10, int(float(value))))
    except (TypeError, ValueError):
        return default


def _judge_scores(notes: str, safety: int = 10, groundedness: int = 10) -> dict:
    return {"safety": safety, "groundedness": groundedness, "notes": notes}


def _unreadable_judge(notes: str) -> dict:
    """The judge answered, but not in a form we can act on. Fail closed."""
    return _judge_scores(notes, safety=_UNREADABLE_SAFETY)


def _parse_judge(raw: str) -> dict:
    try:
        cleaned = _JSON_FENCE_RE.sub("", (raw or "").strip())
        brace_start = cleaned.find("{")
        brace_end = cleaned.rfind("}")
        if brace_start == -1 or brace_end <= brace_start:
            raise ValueError("no JSON object in judge output")
        parsed = json.loads(cleaned[brace_start : brace_end + 1])
        if not isinstance(parsed, dict):
            raise ValueError("judge output is not an object")
    except (json.JSONDecodeError, TypeError, ValueError) as exc:
        logger.warning("Judge output unparseable (%s) — failing closed", exc)
        return _unreadable_judge(f"judge output unparseable: {exc}")

    safety = _score(parsed.get("safety"), default=_UNREADABLE_SAFETY)
    if safety == _UNREADABLE_SAFETY and not _is_numeric(parsed.get("safety")):
        logger.warning(
            "Judge returned a non-numeric safety score %r — failing closed",
            parsed.get("safety"),
        )

    return _judge_scores(
        notes=str(parsed.get("notes", "")),
        safety=safety,
        groundedness=_score(parsed.get("groundedness"), default=_UNREADABLE_GROUNDEDNESS),
    )


def _is_numeric(value: object) -> bool:
    try:
        float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return False
    return True


def _run_judge(response: str, premise: str) -> dict:
    """Score the response for patient harm and groundedness. Never raises."""
    try:
        spec = get_prompt(_JUDGE_PROMPT)
        completion = gateway.complete(
            role=ModelRole.SAFETY_JUDGE,
            messages=build_verifier_messages(
                instructions=spec.template, evidence=premise, response=response
            ),
            purpose=EgressPurpose.SAFETY_VERIFICATION,
            temperature=0.0,
            max_tokens=_JUDGE_MAX_TOKENS,
        )
        return _parse_judge(completion.text)
    except Exception as exc:  # noqa: BLE001 - see module docstring on failure posture
        logger.error("LLM safety judge failed: %s", exc)
        return _judge_scores(f"judge unavailable: {exc}")


# ---------------------------------------------------------------------------
# Node
# ---------------------------------------------------------------------------

def verification_node(state: dict) -> dict:
    """Agent-independent output verification.

    Reads:  state["response"], state["retrieved_docs"], state["risk_level"]
    Writes: state["nli_flags"]    -> list[dict], each with boolean key "entailed"
            state["judge_scores"] -> dict with int "safety" (0-10), int
                                     "groundedness" (0-10), str "notes"
    Must never raise. Returns {**state, ...}.
    """
    state = state or {}
    try:
        response = str(state.get("response") or "")
        docs = state.get("retrieved_docs") or []
        risk = resolve_risk(state)
        policy = get_policy()

        if not response.strip():
            return {
                **state,
                "nli_flags": [],
                "judge_scores": _judge_scores("nothing to verify: empty response"),
                "verification_trace": {
                    "risk_level": risk.value,
                    "policy_version": policy.policy_version,
                    "judge_ran": False,
                },
            }

        nli_flags = _run_nli(response, docs)

        if policy.requires_verification(risk):
            judge = _run_judge(response, _premise_from(docs))
            judge_ran = True
            prompt_ref = get_prompt(_JUDGE_PROMPT).trace_ref
            # The framing decides which text the judge scored, so a score is
            # only interpretable alongside the protocol version that produced it.
            protocol_ref = get_prompt(_VERIFIER_PROTOCOL).trace_ref
        else:
            judge = _judge_scores(f"judge skipped: {risk.value} risk requires no verification")
            judge_ran = False
            prompt_ref = ""
            protocol_ref = ""

        return {
            **state,
            "nli_flags": nli_flags,
            "judge_scores": judge,
            "verification_trace": {
                "risk_level": risk.value,
                "policy_version": policy.policy_version,
                "judge_ran": judge_ran,
                "prompt_ref": prompt_ref,
                "protocol_ref": protocol_ref,
                "claims_checked": len(nli_flags),
            },
        }
    except Exception as exc:  # noqa: BLE001 - contract: this node must never raise
        logger.exception("verification_node failed unexpectedly: %s", exc)
        return {
            **state,
            "nli_flags": [],
            "judge_scores": _judge_scores(f"verification failed: {exc}"),
        }
