"""Agent-independent output verification.

Two audited defects come from verification having been an *agent's*
responsibility rather than the pipeline's:

P1-1  `judge_scores` was never written to graph state. `output_guardrails`
      reads `state["judge_scores"]` and defaults the safety score to 10 when it
      is missing, so the judge BLOCK and WARN branches could not fire in
      production — dead code guarding nothing.

P1-2  `nli_flags` was written only by `clinical_agent`. Every other agent
      (graphrag, summarizer, tool, sql, multimodal, critic) produced answers the
      NLI entailment gate never looked at.

`verification_node` runs after whichever agent produced the answer, so both
signals exist for every response regardless of which agent ran. It observes and
scores; it never edits the response.

Failure posture: the LLM judge fails *open* (safety 10) with the error recorded
in `notes`, because a provider outage must not blanket-block all clinical
traffic. That is not a hole: during an outage the LLM council's safety member
returns a FAIL verdict, which `output_guardrails` treats as a hard block. The
council is the fail-closed control; the judge is a second opinion.
"""
from __future__ import annotations

import json
import logging
import re

from mao.eval.nli_checker import check_all_claims
from mao.prompts import get_prompt
from mao.providers import gateway
from mao.providers.registry import ModelRole
from mao.safety.policy import RiskLevel, get_policy

logger = logging.getLogger(__name__)

_JSON_FENCE_RE = re.compile(r"^```(?:json)?\s*|\s*```$", re.MULTILINE)

_JUDGE_PROMPT = "judge.safety"
_JUDGE_USER_PROMPT = "council.user_turn"
_JUDGE_MAX_TOKENS = 300

# Claim extraction: sentences long enough to assert something, capped so a long
# answer cannot turn one request into a hundred cross-encoder passes.
_MIN_CLAIM_CHARS = 20
_MAX_CLAIMS = 10
_MAX_PREMISE_DOCS = 4
_MAX_DOC_CHARS = 300

# The mandatory clinical disclaimer. It lives here, not in `clinical_agent`, so
# that `output_guardrails` can re-assert it without importing an agent (P0-2).
CLINICAL_DISCLAIMER = """

---
**IMPORTANT — AI Decision Support Only**
This response is generated by an AI system to assist clinical decision-making.
It is NOT a medical diagnosis and must NOT replace professional medical judgement.
All findings must be reviewed and confirmed by a licensed physician or specialist
before any clinical action is taken.
"""

# Stable substring used to detect the disclaimer regardless of formatting drift.
DISCLAIMER_MARKER = "AI Decision Support Only"


# ---------------------------------------------------------------------------
# Risk resolution
# ---------------------------------------------------------------------------

def resolve_risk(state: dict) -> RiskLevel:
    """Read `state["risk_level"]`, falling back to the policy's classification.

    Shared with `output_guardrails` so risk is interpreted in exactly one way.
    """
    raw = state.get("risk_level")
    if isinstance(raw, RiskLevel):
        return raw
    if isinstance(raw, str):
        try:
            return RiskLevel(raw.strip().lower())
        except ValueError:
            logger.warning("Unrecognised risk_level %r — reclassifying from intent", raw)

    metadata = state.get("metadata") or {}
    has_attachment = bool(
        isinstance(metadata, dict)
        and any(metadata.get(k) for k in ("image_b64", "image_url", "report_b64", "report_path"))
    )
    return get_policy().risk_for(str(state.get("intent", "")), has_attachment=has_attachment)


# ---------------------------------------------------------------------------
# NLI entailment
# ---------------------------------------------------------------------------

def _premise_from(docs) -> str:
    """Flatten retrieved chunks (objects or strings) into an NLI premise."""
    if not docs:
        return ""
    parts = []
    for doc in list(docs)[:_MAX_PREMISE_DOCS]:
        if doc is None:
            continue
        text = getattr(doc, "text", None)
        parts.append(str(text if text is not None else doc)[:_MAX_DOC_CHARS])
    return " ".join(p for p in parts if p.strip())


def _claims_from(response: str) -> list[str]:
    return [
        s.strip() for s in response.split(".") if len(s.strip()) > _MIN_CLAIM_CHARS
    ][:_MAX_CLAIMS]


def _run_nli(response: str, docs) -> list[dict]:
    """Entailment flags for the response's claims. Never raises."""
    try:
        premise = _premise_from(docs)
        if not premise:
            return []
        claims = _claims_from(response)
        if not claims:
            return []
        flags = check_all_claims(claims, premise)
        # Normalise: output_guardrails computes an unentailed ratio from these.
        return [
            {**f, "entailed": bool(f.get("entailed"))}
            for f in flags
            if isinstance(f, dict)
        ]
    except Exception as exc:  # noqa: BLE001 - a broken checker must not fail the request
        logger.error("NLI entailment check failed: %s", exc)
        return []


# ---------------------------------------------------------------------------
# LLM judge
# ---------------------------------------------------------------------------

def _score(value, default: int = 10) -> int:
    """Coerce a model-supplied score into an int clamped to 0-10."""
    try:
        return max(0, min(10, int(float(value))))
    except (TypeError, ValueError):
        return default


def _judge_scores(notes: str, safety: int = 10, groundedness: int = 10) -> dict:
    return {"safety": safety, "groundedness": groundedness, "notes": notes}


def _parse_judge(raw: str) -> dict:
    try:
        cleaned = _JSON_FENCE_RE.sub("", (raw or "").strip())
        brace_start = cleaned.find("{")
        brace_end = cleaned.rfind("}")
        if brace_start == -1 or brace_end <= brace_start:
            raise ValueError("no JSON object in judge output")
        parsed = json.loads(cleaned[brace_start : brace_end + 1])
        if not isinstance(parsed, dict):
            raise ValueError("judge output is not an object")
    except (json.JSONDecodeError, TypeError, ValueError) as exc:
        logger.warning("Judge output unparseable (%s)", exc)
        return _judge_scores(f"judge output unparseable: {exc}")

    return _judge_scores(
        notes=str(parsed.get("notes", "")),
        safety=_score(parsed.get("safety")),
        groundedness=_score(parsed.get("groundedness")),
    )


def _run_judge(response: str, premise: str) -> dict:
    """Score the response for patient harm and groundedness. Never raises."""
    try:
        spec = get_prompt(_JUDGE_PROMPT)
        user_turn = get_prompt(_JUDGE_USER_PROMPT).render(context=premise, response=response)
        completion = gateway.complete(
            role=ModelRole.SAFETY_JUDGE,
            messages=[
                {"role": "system", "content": spec.template},
                {"role": "user", "content": user_turn},
            ],
            temperature=0.0,
            max_tokens=_JUDGE_MAX_TOKENS,
        )
        return _parse_judge(completion.text)
    except Exception as exc:  # noqa: BLE001 - see module docstring on failure posture
        logger.error("LLM safety judge failed: %s", exc)
        return _judge_scores(f"judge unavailable: {exc}")


# ---------------------------------------------------------------------------
# Node
# ---------------------------------------------------------------------------

def verification_node(state: dict) -> dict:
    """Agent-independent output verification.

    Reads:  state["response"], state["retrieved_docs"], state["risk_level"]
    Writes: state["nli_flags"]    -> list[dict], each with boolean key "entailed"
            state["judge_scores"] -> dict with int "safety" (0-10), int
                                     "groundedness" (0-10), str "notes"
    Must never raise. Returns {**state, ...}.
    """
    state = state or {}
    try:
        response = str(state.get("response") or "")
        docs = state.get("retrieved_docs") or []
        risk = resolve_risk(state)
        policy = get_policy()

        if not response.strip():
            return {
                **state,
                "nli_flags": [],
                "judge_scores": _judge_scores("nothing to verify: empty response"),
                "verification_trace": {
                    "risk_level": risk.value,
                    "policy_version": policy.policy_version,
                    "judge_ran": False,
                },
            }

        nli_flags = _run_nli(response, docs)

        if policy.requires_verification(risk):
            judge = _run_judge(response, _premise_from(docs))
            judge_ran = True
            prompt_ref = get_prompt(_JUDGE_PROMPT).trace_ref
        else:
            judge = _judge_scores(f"judge skipped: {risk.value} risk requires no verification")
            judge_ran = False
            prompt_ref = ""

        return {
            **state,
            "nli_flags": nli_flags,
            "judge_scores": judge,
            "verification_trace": {
                "risk_level": risk.value,
                "policy_version": policy.policy_version,
                "judge_ran": judge_ran,
                "prompt_ref": prompt_ref,
                "claims_checked": len(nli_flags),
            },
        }
    except Exception as exc:  # noqa: BLE001 - contract: this node must never raise
        logger.exception("verification_node failed unexpectedly: %s", exc)
        return {
            **state,
            "nli_flags": [],
            "judge_scores": _judge_scores(f"verification failed: {exc}"),
        }
