"""
mao/models/mri_predictor.py
----------------------------
EfficientNetB3 MRI classifier — wraps the model from ad/app.py for use by clinical_agent.

Model: Saiarun/b3 on HuggingFace Hub
Classes (alphabetical index order):
  0 → AD   (Alzheimer's Disease)
  1 → CN   (Cognitive Normal)
  2 → EMCI (Early Mild Cognitive Impairment)
  3 → LMCI (Late Mild Cognitive Impairment)

Preprocessing matches ad/app.py exactly:
  BGR→RGB → resize(300,300) → float32 → EfficientNet preprocess_input → expand_dims

Usage:
    from mao.models.mri_predictor import get_predictor
    result = get_predictor().predict(image_b64_string)
    # result["prediction"] == "LMCI"
    # result["confidence"] == 0.87

Requires: tensorflow, tf-keras, opencv-python, huggingface_hub, numpy
"""

from __future__ import annotations

import base64
import logging
import os
import tempfile
from pathlib import Path
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)

# Matches ad/app.py exactly
_IMG_SIZE = 300
_IDX_TO_LABEL: dict[int, str] = dict(enumerate(sorted(["AD", "CN", "EMCI", "LMCI"])))
# {0: 'AD', 1: 'CN', 2: 'EMCI', 3: 'LMCI'}

_LABEL_MAPPING: dict[str, str] = {
    "AD":   "Alzheimer's Disease",
    "CN":   "Cognitive Normal",
    "EMCI": "Early Mild Cognitive Impairment",
    "LMCI": "Late Mild Cognitive Impairment",
}

_DISCLAIMER = (
    "\n\n---\n"
    "**IMPORTANT DISCLAIMER:** This prediction is generated by an AI model for "
    "decision-support purposes only. It is NOT a clinical diagnosis. "
    "Results must be reviewed and confirmed by a licensed medical professional "
    "before any clinical decision is made. Do not act on this output alone."
)

_HF_REPO_ID  = "Saiarun/b3"
_HF_FILENAME = "EfficientNetB3_best.keras"
_CACHE_DIR   = Path(__file__).resolve().parents[3] / "hf_cache"

# Singleton
_predictor: "MRIPredictor | None" = None


def get_predictor() -> "MRIPredictor":
    """Return the module-level singleton, loading it on first call."""
    global _predictor
    if _predictor is None:
        _predictor = MRIPredictor()
    return _predictor


class MRIPredictor:
    """
    Lazy-loading wrapper around EfficientNetB3.

    The Keras model (~25 MB weights) is downloaded from HuggingFace Hub on first use
    and cached locally in hf_cache/. Subsequent calls use the cached file.
    """

    def __init__(self) -> None:
        self._model = None

    def _load(self) -> None:
        """Download (if needed) and load the Keras model."""
        if self._model is not None:
            return

        try:
            from huggingface_hub import hf_hub_download
            from tensorflow.keras.models import load_model  # type: ignore[import]
        except ImportError as exc:
            raise RuntimeError(
                "tensorflow and huggingface_hub are required for MRI prediction. "
                "Run: pip install tensorflow tf-keras huggingface_hub"
            ) from exc

        logger.info("Downloading EfficientNetB3 model from HuggingFace Hub...")
        model_path = hf_hub_download(
            repo_id=_HF_REPO_ID,
            filename=_HF_FILENAME,
            cache_dir=str(_CACHE_DIR),
        )
        logger.info("Loading model from %s", model_path)
        self._model = load_model(model_path, compile=False)
        logger.info("EfficientNetB3 model loaded.")

    def predict(self, image_input: str | bytes | Path) -> dict[str, Any]:
        """
        Predict Alzheimer's stage from a 2D MRI image.

        Args:
            image_input: One of:
                - base64-encoded string (PNG/JPG)
                - raw bytes of an image file
                - file path (str or Path)

        Returns:
            {
              "prediction":  "LMCI",
              "full_label":  "Late Mild Cognitive Impairment",
              "confidence":  0.87,
              "all_scores":  {"AD": 0.05, "CN": 0.03, "EMCI": 0.05, "LMCI": 0.87},
              "disclaimer":  "This prediction is AI-assisted support only...",
              "error":       ""   # non-empty if prediction failed
            }
        """
        try:
            self._load()
            image_array = self._prepare_image(image_input)
            return self._run_inference(image_array)
        except Exception as exc:  # noqa: BLE001
            logger.error("MRI prediction failed: %s", exc)
            return {
                "prediction": "unknown",
                "full_label": "unknown",
                "confidence": 0.0,
                "all_scores": {},
                "disclaimer": _DISCLAIMER,
                "error": str(exc),
            }

    def _prepare_image(self, image_input: str | bytes | Path) -> np.ndarray:
        """Convert any input format to a preprocessed (1, 300, 300, 3) numpy array."""
        import cv2
        from tensorflow.keras.applications.efficientnet import preprocess_input  # type: ignore[import]

        # Resolve to raw bytes
        if isinstance(image_input, (str, bytes)) and not Path(str(image_input)).exists():
            # Treat as base64
            if isinstance(image_input, str):
                # Strip data URI prefix if present
                if "," in image_input:
                    image_input = image_input.split(",", 1)[1]
                raw_bytes = base64.b64decode(image_input)
            else:
                raw_bytes = image_input
            # Decode bytes to numpy via cv2
            arr = np.frombuffer(raw_bytes, dtype=np.uint8)
            img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
        else:
            # File path
            img = cv2.imread(str(image_input))

        if img is None:
            raise ValueError("Could not decode image — check that it is a valid PNG/JPG.")

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (_IMG_SIZE, _IMG_SIZE))
        img = preprocess_input(img.astype(np.float32))
        return np.expand_dims(img, axis=0)  # (1, 300, 300, 3)

    def _run_inference(self, image_array: np.ndarray) -> dict[str, Any]:
        """Run the model and format results."""
        probs: np.ndarray = self._model.predict(image_array, verbose=0)[0]
        pred_idx = int(np.argmax(probs))
        pred_label = _IDX_TO_LABEL[pred_idx]
        all_scores = {
            _IDX_TO_LABEL[i]: round(float(p), 4)
            for i, p in enumerate(probs)
        }
        return {
            "prediction":  pred_label,
            "full_label":  _LABEL_MAPPING[pred_label],
            "confidence":  round(float(probs[pred_idx]), 4),
            "all_scores":  all_scores,
            "disclaimer":  _DISCLAIMER,
            "error":       "",
        }


if __name__ == "__main__":
    import sys
    logging.basicConfig(level=logging.INFO)
    if len(sys.argv) < 2:
        print("Usage: python -m mao.models.mri_predictor <image_path>")
        sys.exit(1)
    result = get_predictor().predict(sys.argv[1])
    print(f"Prediction: {result['full_label']} ({result['prediction']})")
    print(f"Confidence: {result['confidence'] * 100:.1f}%")
    print("All scores:")
    for label, score in result["all_scores"].items():
        print(f"  {label}: {score * 100:.2f}%")
