"""initial_schema

Revision ID: ac3ac21f8acb
Revises: 
Create Date: 2026-04-27 13:23:07.176546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3ac21f8acb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('pii_scrubbed_query', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('agent_used', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('report_card', sa.JSON(), nullable=True),
    sa.Column('council_verdict', sa.JSON(), nullable=True),
    sa.Column('nli_flags', sa.JSON(), nullable=True),
    sa.Column('uncertainty_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('guardrail_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('guardrail_name', sa.String(), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_judge_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('accuracy', sa.SmallInteger(), nullable=True),
    sa.Column('completeness', sa.SmallInteger(), nullable=True),
    sa.Column('safety', sa.SmallInteger(), nullable=True),
    sa.Column('clarity', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('accuracy BETWEEN 1 AND 10', name='ck_accuracy_range'),
    sa.CheckConstraint('clarity BETWEEN 1 AND 10', name='ck_clarity_range'),
    sa.CheckConstraint('completeness BETWEEN 1 AND 10', name='ck_completeness_range'),
    sa.CheckConstraint('safety BETWEEN 1 AND 10', name='ck_safety_range'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating IN (-1, 1)', name='ck_feedback_rating'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_used', sa.String(), nullable=True),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('answer_relevancy', sa.Float(), nullable=True),
    sa.Column('context_precision', sa.Float(), nullable=True),
    sa.Column('context_recall', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_metrics')
    op.drop_table('response_feedback')
    op.drop_table('llm_judge_scores')
    op.drop_table('guardrail_events')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
